name: 'Create Other Repo Branch'

description: 'Attempt creating a branch on another repository'

steps:
  - uses: GuillaumeFalourd/create-other-repo-branch-action@4aaae2f389943fd2448c07844a865be73d907a3f #v1.5
    with:
      repository_owner: TelmoMtzLarrinaga
      repository_name: jubilant-octo-rotary-phone
      new_branch_name: sign/release-v1.0.0@66096563948c7d3f4dc2bce72e6cddc7a732e52304371ba0d20c5c3d155fad5d
      ignore_branch_exits: true

