name: Action test on Ubuntu

on: [push, workflow_dispatch]

jobs:
  test-default:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/create-other-repo-branch-action@main
        with:
          repository_owner: TelmoMtzLarrinaga
          repository_name: jubilant-octo-rotary-phone
          new_branch_name: sign
          access_token: ${{ secrets.ACTIONS_PAT}}
          ignore_branch_exists: true